autotext/urls.py
from django.urls import path, include
from . import views

app_name = 'autotext'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('myReferences', views.myReferences, name='myReferences'),
    path('myReferences/addReference', views.addReference, name='addReference'),
    path('myReferences/editReference', views.editReference, name='editReference'),
    path('myReferences/deleteReference',
         views.deleteReference, name='deleteReference'),
    path('myReferences/addManyReferences',
         views.addManyReferences, name='addManyReferences'),
    path('myReferences/setWebography', views.setWebography, name='setWebography'),
    path('myReferences/addWebography', views.addWebography, name='addWebography'),
    path('myReferences/editWebography',
         views.editWebography, name='editWebography'),
    path('myReferences/deleteWebography',
         views.deleteWebography, name='deleteWebography'),



]

projet_individuel_fcouthouis/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('autotext.urls')),
    path('admin/', admin.site.urls),
]

autotext/models/reference.py
import io
import re
import pybtex.database.input.bibtex
import six
from django.db import models


class Reference(models.Model):
    url = models.URLField(max_length=400)
    _bibtex_reference = models.TextField(null=True,)
    _apa_reference = models.TextField(blank=True, null=True,)
    webography = models.ForeignKey(
        "Webography", on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):
        string = "Reference : " + str(self.pk) + " with url : " + str(self.url)
        return string

    @property
    def bibtex_reference(self):
        if self._bibtex_reference is None or self._bibtex_reference == "":
            self._bibtex_reference = self._get_bibtex_reference()
            self.save()

        return self._bibtex_reference

    @bibtex_reference.setter
    def bibtex_reference(self, value):
        self._bibtex_reference = value

    @property
    def apa_reference(self):
        if self._apa_reference is None or self._apa_reference == "":
            self._apa_reference = self._get_formatted_reference('apa')
            self.save()

        return self._apa_reference

    @apa_reference.setter
    def apa_reference(self, value):
        self._apa_reference = value

    def _retrieve_content(self):
        """Get the raw content of the article (html or binaries from pdf). """
        raise NotImplementedError(
            'subclasses must override _retrieve_content()!')

    def _get_bibtex_reference(self):
        """
        Get the bibtex reference. Returns a string.
        """
        raise NotImplementedError(
            'subclasses must override get_bibtext_reference()!')

    def _get_formatted_reference(self, format_style='apa'):
        """
        Get the reference formatted into one of the possible formats.
        FormatStyle can be 'alpha', 'plain', 'unsrt', 'unsrtalpha' or 'apa'. Default = 'apa'.
        """

        # Return "" if bibtex ref is not referenced, as we need bibtex ref to find apa reference
        if self.bibtex_reference == "undefined" or self.bibtex_reference is None:
            return "undefined"
        else:
            pybtex_style = pybtex.plugin.find_plugin(
                'pybtex.style.formatting', format_style)()
            pybtex_html_backend = pybtex.plugin.find_plugin(
                'pybtex.backends', 'text')()
            pybtex_parser = pybtex.database.input.bibtex.Parser()

            data = pybtex_parser.parse_stream(
                six.StringIO(self.bibtex_reference))

            # Correct the "missing entry : booktitle" error
            key = data.entries.keys()[0]
            if not data.entries[key].fields.get("booktitle"):
                data.entries[key].fields["booktitle"] = ""

            data_formatted = pybtex_style.format_entries(
                six.itervalues(data.entries))

            output = io.StringIO()
            pybtex_html_backend.write_to_stream(data_formatted, output)

            # Remove "\n" at the end of the output value
            formatted_ref = output.getvalue().replace("\n", "")

            # Remove useless array at the begining
            formatted_ref = re.sub(r'\[(.*?)\] ', '', formatted_ref)

            return formatted_ref

    # def get_language(self, text=""):
    #     nlp = spacy.load('en')
    #     nlp.add_pipe(Reference.language_detector)
    #     doc = nlp(text)

    #     return doc._.languages

    def _log_error(self, e):
        print(e)

autotext/models/referencePDF.py
import tempfile
import pdftitle
import gscholar
from requests import get
from requests.exceptions import RequestException
from .reference import Reference
from ..Helpers import sscholar


class ReferencePDF(Reference):
    def _retrieve_content(self):
        """
        Retrieve content (pdf file) on the web.
        """
        try:
            response = get(self.url)
            temp = tempfile.NamedTemporaryFile()
            temp.write(response.content)
            # "After writing, the file handle must be “rewound” using seek() in order to read the data back from it."
            temp.seek(0)

            content = temp

        except RequestException as e:
            self._log_error(
                'Error during requests to {0} : {1}'.format(self.url, str(e)))
            return None

        return content

    def _get_bibtex_reference(self):
        '''Retrieve bibtex reference using pdftitle and SemanticScholar'''
        content = self._retrieve_content()
        title = pdftitle.get_title_from_file(content.name)

        # use SemanticScholar
        bibref = sscholar.get_bib_from_title(title)

        # Try Gscholar if not found on semanticscholar
        if bibref == "undefined":
            sources = gscholar.query(title)
            if sources:
                bibref = sources[0]

        return bibref.rstrip()

autotext/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


from .models.webography import Webography


class UrlListForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control '

    urlList = forms.CharField(initial="",
                              widget=forms.Textarea())


class IndexForm(UrlListForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'

    username = forms.CharField(help_text="Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères « @ », « . », « + », « - » et « _ ».",
                               widget=forms.TextInput(
                                   attrs={'placeholder': "Nom d'utilisateur", 'icon': 'fa fa-user'}))

    password1 = forms.CharField(help_text="Minimum 8 caractères.", widget=forms.PasswordInput(
        attrs={'placeholder': 'Mot de passe', 'icon': 'fa fa-lock'}))
    password2 = forms.CharField(help_text="Même mot de passe que précédemment, pour vérification.", widget=forms.PasswordInput(
        attrs={'placeholder': 'Retapez le mot de passe', 'icon': 'fa fa-lock'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields


class WebographyForm(forms.Form):
    def __init__(self, *args, **kwargs):
        # Retirve user
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'

        self.fields['webography'] = forms.ModelChoiceField(
            required=False, queryset=Webography.objects.filter(user=user))

    name = forms.CharField(required=False,
                           widget=forms.TextInput(attrs={'placeholder': 'Nom'}))


class ReferenceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'

    url = forms.URLField(required=True,
                         max_length=400, widget=forms.Textarea(attrs={'rows': 1, 'placeholder': 'Url'}))
    bibtex_reference = forms.CharField(required=False,
                                       widget=forms.Textarea(attrs={'placeholder': 'Réference bibtex (laisser vide pour une complétion automatique)'}))
    apa_reference = forms.CharField(required=False,
                                    widget=forms.Textarea(attrs={'placeholder': 'Réference apa (laisser vide pour une complétion automatique)'}))
    ref_id = forms.CharField(required=False)

autotext/views.py
from itertools import chain
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.template import loader
from django.http import HttpResponse

from .forms import UrlListForm, IndexForm, SignUpForm, ReferenceForm, WebographyForm

from .models.webography import Webography
from .models.referencePDF import ReferencePDF
from .models.referenceWeb import ReferenceWeb


def set_to_session(request, webography):
    ''' Set webography info into a session variable'''
    request.session['webography_id'] = webography.id
    request.session['webography_name'] = webography.name


def get_webography_from_session(request):
    webography_id = request.session['webography_id']
    webography = Webography.objects.get(id=webography_id)
    return webography


def index(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = IndexForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = form.cleaned_data
            webography = Webography()
            webography.save()
            webography.add_refererences_from_urls(
                raw_urls=data['urlList'])
            apa = webography.get_formatted_webography()
            bib = webography.get_bibtex_webography()

            webography.delete()

            return render(request, 'autotext/index.html', {'form': form,
                                                           'webography_apa': apa,
                                                           'webography_bib': bib})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = IndexForm()

    return render(request, 'autotext/index.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


def myReferences(request):
    # Check if user is logged in
    if not request.user.is_authenticated:
        return redirect('/accounts/login')
    else:
        template = loader.get_template('autotext/myReferences.html')

        if not request.session.get('webography_id', None):
            webographies = Webography.objects.filter(user=request.user)
            if webographies:
                # Take first webography
                webography = webographies[0]
                set_to_session(request, webography)
            else:
                context = {
                    'no_webography': 1,
                    'webography_form': WebographyForm(user=request.user),
                    'reference_form': ReferenceForm(),
                    'references_form': UrlListForm()
                }
                return HttpResponse(template.render(context, request))

        else:
            webography = get_webography_from_session(request)

        referencepdf_set = webography.referencepdf_set.all()
        referenceweb_set = webography.referenceweb_set.all()
        # # Chain the sets
        reference_set = list(
            chain(referencepdf_set, referenceweb_set))

        context = {
            'webography_form': WebographyForm(user=request.user),
            'reference_set': reference_set,
            'reference_form': ReferenceForm(),
            'references_form': UrlListForm()
        }
        return HttpResponse(template.render(context, request))


def setWebography(request):
    if request.method == 'POST':
        form = WebographyForm(request.POST, user=request.user)

        if form.is_valid():
            set_to_session(request, form.cleaned_data["webography"])

    return redirect('/myReferences')


def addReference(request):
    if request.method == 'POST':
        form = ReferenceForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            webography = get_webography_from_session(request)
            url = data["url"]
            bibtex_reference = data["bibtex_reference"]
            apa_reference = data["apa_reference"]

            webography.add_reference(
                url=url, apa_reference=apa_reference, bibtex_reference=bibtex_reference)

    return redirect("/myReferences")


def editReference(request):
    if request.method == 'POST':
        form = ReferenceForm(request.POST)

        if form.is_valid():
            reference = get_ref_object(request, "edit_ref")

            data = form.cleaned_data
            reference.url = data["url"]
            reference.bibtex_reference = data["bibtex_reference"]
            reference.apa_reference = data["apa_reference"]

            reference.save()

    return redirect("/myReferences")


def deleteReference(request):
    if request.method == 'POST':
        reference = get_ref_object(request, "delete_ref")
        reference.delete()
    return redirect("/myReferences")


def get_ref_object(request, action):
    ref_data = request.POST.get(action)

    if not ref_data:
        return None

    ref_id = ref_data.split(";")[0]
    ref_classtype = ref_data.split(";")[1]

    if "ReferencePDF" in ref_classtype:
        reference = ReferencePDF.objects.get(id=ref_id)
    elif "ReferenceWeb" in ref_classtype:
        reference = ReferenceWeb.objects.get(id=ref_id)
    else:
        reference = None

    return reference


def addWebography(request):
    if request.method == 'POST':
        form = WebographyForm(request.POST, user=request.user)

        if form.is_valid():
            data = form.cleaned_data
            webography = Webography(name=data['name'], user=request.user)
            webography.save()
            set_to_session(request, webography)

    return redirect("/myReferences")


def editWebography(request):
    if request.method == 'POST':
        form = WebographyForm(request.POST, user=request.user)

        if form.is_valid():
            webography = get_webography_from_session(request)
            data = form.cleaned_data
            webography.name = data["name"]
            webography.save()

    return redirect("/myReferences")


def deleteWebography(request):
    if request.method == 'POST':
        webography_id = request.session.get('webography_id', None)

        webography = Webography.objects.get(id=webography_id)
        webography.delete()
        # Reset session variable
        del request.session['webography_id']
    return redirect("/myReferences")


def addManyReferences(request):
    if request.method == 'POST':
        form = UrlListForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            webography = get_webography_from_session(request)
            webography.add_refererences_from_urls(
                raw_urls=data['urlList'])

    return redirect("/myReferences")

autotext/templates/autotext/base.html
<!-- templates/registration/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="fr">

  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Weboto</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous" />
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
      integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous">
    </script>

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
      integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'autotext/style.css' %}" />

    <link rel="shortcut icon" type="image/png" href="{% static 'autotext/images/logo.png' %}" />


  </head>

  <header>
    <div class="header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">
          <img src="{% static 'autotext/images/logo_white.png' %}" width="30" height="30"
            class="d-inline-block align-top" alt="" />
          Weboto
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/myReferences">Gérer mes webographies</a>
            </li>
          </ul>
        </div>
        {% if user.is_authenticated %}
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
            <img class="nav-icon" width="32" src="https://avatars.dicebear.com/v2/jdenticon/{{user.username}}.svg">
            <span class="connect">{{user.username}}</span>
          </a>
          <div id="login-dp" class="row dropdown-menu">
            <div class="">
              <a class="nav-link" href="accounts/logout/">
                <i class="fa fa-sign-out">
                  <span class="userMenuText"> Déconnexion </span>
                </i>
              </a>
            </div>
          </div>

          {% else %}
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
              <i class="fa fa-user nav-icon">
                <span class="connect"> Se connecter </span>
              </i>
            </a>
            <div id="login-dp" class="row dropdown-menu">
              <div class="col-md-12">
                {% include "../registration/loginForm.html" %}
              </div>
            </div>
            {% endif %}
      </nav>
    </div>
  </header>

  <br />

  {% block content %} {% endblock %}

  <!-- <footer>F. Couthouis</footer> -->

</html>

autotext/templates/autotext/index.html
<!-- templates/registration/index.html -->
{% extends 'autotext/base.html' %} {% block content %}

<body class="index-body">
  <div class="container-fluid">
    <div class="">
      <form class="post-form col-md" method="post">
        {% csrf_token %}




        <div class="row">
          <div class="col-sm">
            <div class="controls">
              <button width="20" type="submit" class="btn btn-custom btn-block">
                Génerer ma webographie
              </button>
            </div>

            <textarea required class="form-control index-textarea" rows="20" placeholder="Copier ici votre liste d'urls puis cliquez sur Générer ma webographie : http://... http://...
              ..." type="urlList" id="id_urlList" name="urlList">{{ form.urlList.value }}</textarea>

          </div>

          {%if webography_bib %}

          <div class="index-tabs col-sm">
            <div class="index-tab-2">
              <label for="index-tab2-1">Bibtex</label>
              <input id="index-tab2-1" name="index-tabs-two" type="radio" checked="checked" />
              <div class="index-textarea-container">
                <span title="Copier dans le presse papier" class="copy-btn" onclick="copyTextarea('textarea-bib')"><i
                    class="fa fa-copy"></i></span>
                <textarea id="textarea-bib" class="col-md form-control index-textarea" rows="20" readonly>{{ webography_bib }}
                    </textarea>
              </div>

            </div>
            <div class="index-tab-2">
              <label for="index-tab2-2">Apa</label>
              <input id="index-tab2-2" name="index-tabs-two" type="radio" />
              <div class="index-textarea-container">
                <span title="Copier dans le presse papier" class="copy-btn btn"
                  onclick="copyTextarea('textarea-apa')"><i class="fa fa-copy"></i></span>
                <textarea id="textarea-apa" class="col-sm-5 form-control col-md index-textarea" rows="20" readonly>{{ webography_apa }}
                    </textarea>
              </div>
            </div>
          </div>
          <!--index tab -->
          {%endif%}

          <br />

        </div>

      </form>
    </div>
  </div>


</body>

<script type="text/javascript" src="static/autotext/scripts/copyToClipboard.js"></script>

{% endblock %}

autotext/templates/autotext/reference_form.html
<!-- templates/autotext/reference_form.html -->
{% load util %}
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        {%if ref%}
          <h3 class="modal-title" id="addRefModalLabel">Modifier la référence</h5>
        {%else%}
            {%if manyRef%}
              <h3 class="modal-title" id="addRefModalLabel">Ajouter plusieurs références</h5>
            {%else%}
              <h3 class="modal-title" id="addRefModalLabel">Ajouter une référence</h5>
            {%endif%}
        {%endif%}
      </div>
      <div class="modal-body">
        {%if manyRef%}
          <form action="/myReferences/addManyReferences" method="post">  
          {% csrf_token %}
              <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="fa fa-book"></i>
                    </span>
                  </div>
                  {{ references_form.urlList }} 
                </div>
                <br/>
            
                <div class="modal-footer">
                  <button type="submit" name="add_ref" value="new_ref" class="btn btn-lg btn-block btn-dark btn-labeled">
                      <i class="btn-label fa fa-plus-circle"></i>
                    Ajouter 
                  </button>
                  
                </div>
              </div>

        {%else%}
          {%if ref%}
            <form action="/myReferences/editReference" method="post">  
          {%else%}
            <form action="/myReferences/addReference" method="post">  
          {%endif%}
              {% csrf_token %}
              


                <div class="input-group" title="Un URL n'est pas modifiable, veuillez créer une nouvelle référence et supprimer celle-ci si besoin.">
                  <div class="input-group-prepend" >
                    <span class="input-group-text">
                      <i class="fa fa-link"></i>
                    </span>
                  </div>
                  {%if ref%}
                    <input class="form-control" cols="40" type="url" id="id_url" name="url" value="{{ ref.url }}" 
                    disabled="disabled">
                  {%else%}
                    {{ form.url }} 
                  {%endif%}
                </div>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="fa fa-book"></i>
                    </span>
                  </div>
                  {%if ref%}
                    <textarea class="form-control" type="bibtex_reference" rows="10" cols="40" id="id_bibtex_reference" name="bibtex_reference">{{ ref.bibtex_reference }}</textarea>
                  {%else%}
                    {{ form.bibtex_reference }} 
                  {%endif%}
                </div>
                <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="fa fa-book"></i>
                      </span>
                    </div>
                    {%if ref%}
                    <textarea class="form-control" type="apa_reference" rows="10" cols="40" id="id_apa_reference" name="apa_reference">{{ ref.apa_reference }}</textarea>
                    {%else%}
                      {{ form.apa_reference }} 
                    {%endif%}
                  </div>
                  <br/>
              
                  <div class="modal-footer">
                  {%if ref%}
                    <button type="submit" name="edit_ref" value="{{ref.id}};{{ref|get_type}}" class="btn btn-lg btn-block btn-dark btn-labeled">
                        <i class="btn-label fa fa-edit"></i>
                      Modifier
                    </button>
                  {%else%}
                    <button type="submit" name="add_ref" value="new_ref" class="btn btn-lg btn-block btn-dark btn-labeled">
                        <i class="btn-label fa fa-plus-circle"></i>
                      Ajouter
                    </button>
                  {%endif%}
                {%endif%}
                  
                </div>
              </div>
            
            </form>           
        
      </div>
    </div>
  </div>
  

autotext/templates/autotext/webography_form.html
<!-- templates/autotext/webography_form.html -->
{% load util %}
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        {%if edit%}
          <h3 class="modal-title" id="editWebModalLabel">Modifier le nom de ma webographie</h5>
        {%else%}
          <h3 class="modal-title" id="addWebModalLabel">Ajouter une webographie</h5>
        {%endif%}
      </div>
      <div class="modal-body">
        {%if edit%}
          <form action="/myReferences/editWebography" method="post", autocomplete="off">  
        {%else%}
          <form action="/myReferences/addWebography" method="post", autocomplete="off">  
        {%endif%}
            {% csrf_token %}

              <div class="input-group" title="Nom de la webographie.">
                <div class="input-group-prepend" >
                  <span class="input-group-text">
                    <i class="fas fa-file-signature"></i>
                  </span>
                </div>
                {%if edit%}
                  <input class="form-control" cols="4" id="id_name" name="name" value="{{ request.session.webography_name }}" >
                {%else%}
                  {{ form.name }} 
                {%endif%}
              </div>

              <br>
              
                {%if edit%}
                  <button type="submit" name="edit_web" class="btn btn-lg btn-block btn-dark btn-labeled">
                      <i class="btn-label fa fa-edit"></i>
                    Modifier
                  </button>
                {%else%}
                  <button type="submit" name="add_web" class="btn btn-lg btn-block btn-dark btn-labeled">
                      <i class="btn-label fa fa-plus-circle"></i>
                    Ajouter
                  </button>
                {%endif%}
                  
                </div>
              </div>
            
            </form>           
        
      </div>
    </div>
  </div>
  